apps/contact/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^contact$', views.ContactView.as_view(), name='contact_form'),
    url(r'^contact/thanks$', views.ContactThanksView.as_view(), name='contact_thanks'),
]

apps/website/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomeView.as_view(), name='home'),
]

corley/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.website.urls', namespace='website')),
    url(r'^', include('apps.contact.urls', namespace='contact')),
]

apps/contact/models.py
from django.db import models

# Create you models here

apps/website/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

apps/contact/forms.py
from django import forms


class EmailForm(forms.Form):
    subject = forms.CharField(max_length=50)
    message = forms.CharField(widget=forms.Textarea())
    sender = forms.EmailField(required=True)

apps/contact/views.py
from django.core.mail import send_mail, BadHeaderError
from django.views import generic
from django.http import HttpResponse
from django.core.urlresolvers import reverse
from . import forms


class ContactView(generic.FormView):
    template_name = 'contact_form.html'
    form_class = forms.EmailForm

    def form_valid(self, form):
        message = "Reply to: {sender}\n".format(sender=form.cleaned_data.get('sender'))
        message += "\n\nMessage:\n{0}".format(form.cleaned_data.get('message'))
        try:
            send_mail(
                subject=form.cleaned_data.get('subject').strip(),
                message=message,
                from_email='FROM_EMAIL@domain.com',
                recipient_list=['RECIPIENT@domain.com'],
            )
        except BadHeaderError:
                return HttpResponse('Invalid header found.')

        return super(ContactView, self).form_valid(form)

    def form_invalid(self, form):
        return HttpResponse("<h4>Form invalid...</h4>")

    def get_success_url(self):
        return reverse('contact:contact_thanks')


class ContactThanksView(generic.TemplateView):
    template_name = 'contact_thanks.html'

apps/website/views.py
from django.shortcuts import render
from django.views import generic


class HomeView(generic.TemplateView):
    template_name = 'home.html'

apps/contact/templates/contact_form.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}Contact{% endblock %}

{% block head %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div id="results" class="col-md-6 contact-form">
                <h4>Email Us</h4>
                <form id="contact_form" action="" method="POST">{% csrf_token %}
                    <input class="form-control" id="id_sender" name="sender" type="email" placeholder="Your Email Address" required /><br>
                    <input class="form-control" id="id_subject" maxlength="50" name="subject" type="text" placeholder="Subject" required/><br>
                    <textarea class="form-control" cols="40" id="id_message" name="message" rows="10" placeholder="Message..." required></textarea><br>
                    <button style="margin-top: 5px;" type="submit" class="btn btn-info btn-md">Send Email</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        var frm = $('#contact_form');
        frm.submit(function () {
            $.ajax({
                type: frm.attr('method'),
                url: frm.attr('action'),
                data: frm.serialize(),
                success: function (data) {
                    $("#results").html(data);
                },
                error: function (data) {
                    $("#results").html("Something went wrong!");
                }
            });
            return false;
        });
    </script>
{% endblock %}

apps/contact/templates/contact_thanks.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>Success</title>
</head>
    <body>
    <div>
        <h4>Thanks your email has been sent!!</h4>
    </div>

    </body>
</html>

apps/website/templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block content %}
    <div class="row">
        <div class="col-md-6">
            <h4>TLC Home Inspections</h4>
            <button class="btn btn-success">press</button>
        </div>
    </div>
{% endblock %}

corley/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="nwalk">
    <link rel="icon" href="{% static 'media/pictures/favicon.ico' %}">
    {% block head %}
    {% endblock %}
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'corley.css' %}" rel="stylesheet">
{#    <link href="{% static "bootstrap/css/bootstrap.css" %}" rel="stylesheet">#}
{#    <link href="{% static "bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">#}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossorigin="anonymous">
</head>
<body>
 <!-- Fixed navbar -->
    <nav class="navbar navbar-default-1 navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'website:home' %}">TLC</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="nc"><a href="#">link</a></li>
{#            {% if request.user.is_authenticated %}#}
                <li><a href="#">link</a></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">dropdown<span class="caret"></span></a>
                  <ul class="dropdown-menu">
                      <li><a href="#">link</a></li>
                      <li><a href="#">link</a></li>
                  </ul>
                </li>
{#            {% endif %}#}
{#            <li><a href="#">link</a></li>#}
{#              <li class="dropdown">#}
{#                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">projects<span class="caret"></span></a>#}
{#                  <ul class="dropdown-menu">#}
{#                      <li><a href="#">link</a></li>#}
{#                      <li><a href="#">link</a></li>#}
{#                      <li><a href="#">link</a></li>#}
{#                      <li class="divider"></li>#}
{#                      <li><a href="">link</a></li>#}
{#                  </ul>#}
{#              </li>#}
          </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#"></a></li>
                <li><a href="{% url 'contact:contact_form' %}">contact</a></li>
                {#            <li><button style="margin-top: 10px;" type="button" class="btn btn-info btn-sm" onclick="window.location.href=''">feedback</button></li>#}
            <!--<li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Search<strong class="caret"></strong></a>
              <ul class="dropdown-menu">
                <li>
                  <form class="navbar-form navbar-left" role="search">
                    <div class="form-group">
                      <input style="margin-bottom: 5px;" type="text" class="form-control" placeholder="Feature does not work yet"/>
                    </div> <button type="submit" class="btn btn-default">Submit</button>
                   </form>
                </li>
              </ul>
            </li>-->
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
<div class="container">
    <div class="col-md-12 column" style="padding-top: 60px"></div>
    {% block content %}{% endblock %}
</div>
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"
          integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s="
          crossorigin="anonymous">
    </script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
         integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
         crossorigin="anonymous">
    </script>
{#    <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>#}
{% block scripts %}{% endblock %}
</body>
</html>

corley/templates/base2.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'corley.css' %}" rel="stylesheet">
    <link href="{% static "bootstrap/css/bootstrap.css" %}" rel="stylesheet">
    <link href="{% static "bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">

</head>
<body>
<div class="container">
{% block content %}{% endblock %}
</div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
</body>
</html>